---
title: "data-wrangling"
output: pdf_document
---

```{r setup, include = FALSE}
# load packages
library(readxl)
library(mdsr)
library(tidyverse)
library(dplyr)
library(knitr)
library(ggplot2)
library(janitor)
library(vroom) # fast reading/importing data
library(sf) # spacial data
library(tigris) # geojoin
library(leaflet) # interactive maps
library(htmlwidgets) # interactive map labels

# set code chunk defaults
knitr::opts_chunk$set(tidy = F, # display code as typed
                      size = "small", # slightly smaller code font
                      message = FALSE,
                      warning = FALSE,
                      comment = "\t") 
# set black & white default plot theme 
# theme_set(theme_classic()) # uncomment this line if desired
# improve digit and NA display 
options(scipen = 1, knitr.kable.NA = '')
```

## Data Import
```{r, eval = TRUE}
# Incarceration Trends
incarceration_trends <- vroom("incarceration_trends.csv")
incarceration_rates <- read_csv("prison_policy_initiative_incarceration_by_race.csv")
incarceration_populations <- read_csv("bjs_total_correctional_population_counts_by_status_TM 5_26_21.csv")
incarceration_rates_race <- read_csv("prison_policy_initiative_incarceration_by_race.csv") # data from 2010
rates_by_race <- read_csv("sentencing_project_rates_by_race.csv")
ratio_bw <- read_csv("ratio_bw.csv")
```

## Data Wrangling
```{r, eval = TRUE}
# read in shapefile
unzip(zipfile = "geography resource/cb_2018_us_county_500k.zip")
county_shapefile <- read_sf("cb_2018_us_county_500k.shp") %>%
  janitor::clean_names() 

# take out statefp and countyfp and rename geoid column into fips
county_shapefile <- county_shapefile %>%
  select(-statefp, -countyfp) %>%
  mutate(fips = as.numeric(geoid))
head(county_shapefile)
```

## Incarceration Trends Wrangling
```{r, eval = TRUE}
incarceration_trends <- incarceration_trends %>%
  separate(county_name, c("county",NA), sep = " ") %>%
  filter(state != "AK", state != "HI")

write_csv(incarceration_trends, "incarceration_trends_wrangled.csv")
```

## Incarceration by State Wrangling
```{r, eval = TRUE}
<<<<<<< HEAD

#rename necessary columns

=======
#rename necessary columns
<<<<<<< HEAD
incarceration_rates_race <- incarceration_rates_race %>% 
  rename(ID = "...3",
         rate_per_100 = "...26") %>% 
  #delete United States row and remove states and territories not in Continental United States
  filter(ID != "United States", 
         ID != "Puerto Rico", 
         ID != "Geography", 
         ID != "Hawaii", 
         ID != "Alaska") %>%
=======
>>>>>>> 975a559764bd19706ce0b77eb0d59c6794f8c7fc
incarceration_rates_race <- incarceration_rates_race %>% rename(ID = "...3" ) %>% rename(rate_per_100 = "...26")
#delete United States row and remove states and territories not in Continental United States
incarceration_rates_race <- incarceration_rates_race %>% filter(ID!="United States", ID!="Puerto Rico", ID!="Geography", ID!="Hawaii", ID!="Alaska")
>>>>>>> 3ebf0e7012c00096bb963bac6e3873e4e0c4346a
#Make state names lowercase to match geom dataset and change rate column to numeric
  mutate(ID = tolower(ID),
         rate_per_100 = as.numeric(rate_per_100),
         #Take out commas from rates column
         rate_per_100 = gsub(",","", as.character(rate_per_100)))
```

#Population Time-Series wrangling
```{r, eval = TRUE}
incarceration_populations <- incarceration_populations %>% 
  rename(total_incarcerated = "...7",
         year = "Bureau of Justice Statistics",
         total_supervised = "...2",
         local_jail = "...8",
         state_prison = "...10",
         federal_prison = "...11") %>%
  filter(total_incarcerated != "Total/c", !row_number() %in% c(1)) %>%
  separate(year, c("year",NA), sep = "/d") %>%
  mutate(
    total_incarcerated = as.numeric(gsub(",","", as.character(total_incarcerated))),
    total_supervised = as.numeric(gsub(",","", as.character(total_supervised))),
    local_jail = as.numeric(gsub(",","", as.character(local_jail))),
    state_prison = as.numeric(gsub(",","", as.character(state_prison))),
    federal_prison = as.numeric(gsub(",","", as.character(federal_prison))),
    year = as.numeric(year))
```

#Incarceration Rates by Race wrangling
```{r, eval = TRUE}
<<<<<<< HEAD
=======

<<<<<<< HEAD
=======
>>>>>>> 3ebf0e7012c00096bb963bac6e3873e4e0c4346a
rates_by_race <- rates_by_race %>% 
  rename(State = ID) %>%
  mutate(State = tolower(State),
         Black = as.numeric(Black),
         Latino = as.numeric(Latino),
         White = as.numeric(White),
         State = toupper(State)) %>%
  pivot_longer(!ID, names_to = "race", values_to = "rate")

<<<<<<< HEAD
=======
>>>>>>> 975a559764bd19706ce0b77eb0d59c6794f8c7fc
rates_by_race <- rates_by_race %>% rename(ID = State ) 
rates_by_race <- rates_by_race %>% mutate(ID = tolower(rates_by_race$ID))%>% mutate(Black = as.numeric(Black))%>% mutate(Latino = as.numeric(Latino))%>% mutate(White = as.numeric(White))

rates_by_race <- rates_by_race %>%
  pivot_longer(!ID, names_to = "race", values_to = "rate")
>>>>>>> 3ebf0e7012c00096bb963bac6e3873e4e0c4346a

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
        sep="", collapse=" ")
}

rates_by_race$ID <- sapply(rates_by_race$ID, simpleCap)


write_csv(rates_by_race, "rates_by_race_wrangled.csv")

<<<<<<< HEAD

=======
rates_by_race %>% arrange(ID)
>>>>>>> 975a559764bd19706ce0b77eb0d59c6794f8c7fc
```
#Ratio
```{r, eval = TRUE}

ratio_bw <- ratio_bw %>% rename(ID = State ) %>% rename(ratio= "Ratio (B/W)" ) 

ratio_bw <- ratio_bw %>% mutate(ID = tolower(ratio_bw$ID))

ratio_bw <- ratio_bw %>% mutate(ratio = as.numeric(ratio))
```

