---
title: "Maps"
author: "Facts & Stats"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
library(scales)
library(readxl)
library(mdsr)
library(tidyverse)
library(dplyr)
library(knitr)
library(ggplot2)
library(gganimate)
library(gifski)
library(janitor)
library(viridis)
library(sf)
library(tigris) # geojoin
library(leaflet) # interactive maps
library(htmlwidgets) # interactive map labels
```

# Import dataframes
```{r, eval = TRUE}
# Incarceration Trends
incarceration_trends <-read_csv("incarceration_trends.csv")
incarceration_trends_jail_jurisdiction <-read_csv("incarceration_trends_jail_jurisdiction.csv")
incarceration_rates_race # data frame wrangled in `data-wrangling`, 2010 data
county_shapefile 
incarceration_trends_1970
incarceration_trends_2018
incarceration_populations
```

# Static Map by State (2010)
```{r pressure, echo=FALSE}
#Create dataset with coordinate information for states
state_map <- maps::map("state", plot = FALSE, fill = TRUE) %>% 
  st_as_sf()

state_info <- data.frame(Region = state.region,
                         # Match state variable name in map data
                         ID = tolower(state.name), 
                         # Match state variable name in summary data
                         State = state.abb)

#Create dataset with coordinate information for counties
county_map <- maps::map("county", plot = FALSE, fill = TRUE) %>% 
  st_as_sf() 

#delete state name from county name
county_map <-county_map %>%
  separate(ID, c("state","county"), sep = ',')


state_map <- maps::map("state", plot = FALSE, fill = TRUE) %>% 
  st_as_sf()





incarceration_rates_race <- state_map %>% 
  left_join(state_info) %>% 
  left_join(incarceration_rates_race)

rates_by_race_map <- state_map %>% 
  left_join(state_info) %>% 
  left_join(rates_by_race)

ratio_bw_map <- state_map %>% 
  left_join(state_info) %>% 
  left_join(ratio_bw)

class(incarceration_rates_race$Total_Incarcerated)

  
#Map of States and Counties
ggplot(incarceration_rates_race, aes(fill = rate_per_100)) +
geom_sf() +
  scale_fill_viridis(option = "magma", direction = -1) +
  theme_void() +
  labs(title=" Prison Incarceration Rate by State 2010", fill = "Prisoners per \n100,000 residents")
ggsave("Incarceration_2010.png")

ggplot(rates_by_race_map, aes(fill = Black)) +
geom_sf() +
  scale_fill_viridis(option = "mako", direction = -1) +
  theme_void()+
  labs(title="Black Prison Incarceration Rate by State", fill = "Prisoners per \n100,000 residents")

ggplot(ratio_bw_map, aes(fill = ratio)) +
geom_sf() +
  scale_fill_viridis(direction = -1) +
  theme_void()+
  labs(title=" Incarceration Disparity Between Black and white Americans 2020", fill = "Black/white Ratio ")

ggsave("Incarceration_2020.png")

ggplot(incarceration_populations, aes(x=year, y=total_supervised, group=1)) +
  geom_line(color="red", size=2) + 
  scale_x_continuous(breaks=seq(1970, 2018, 5))+
  labs(title="American Incarcerated Population Over Time (1980-2018)", y = "Incarcerated Population", x= "Year")

ggplot(incarceration_populations, aes(x=year, y=total_incarcerated, group=1)) +
  geom_line(color="blue", size=2) + 
  scale_x_continuous(breaks=seq(1970, 2018, 5))+
  labs(title="American Population Under State Supervision Over Time (1980-2018)", y = "Incarcerated Population", x= "Year")

ggplot(data= rates_by_race, aes(x=race, y=rate)) +
  geom_bar(stat="identity", width=0.5)
```

# Leaflet Maps by County (1970 vs 2018)
```{r, eval = TRUE}
# combine the shapefile and the incarceration trends dataframe for both years respectively
incarceration_1970_map <- geo_join(county_shapefile, incarceration_trends_1970, 'fips', 'fips', how = "left")
incarceration_2018_map <- geo_join(county_shapefile, incarceration_trends_2018, 'fips', 'fips', how = "left")

# make a palette
bins <- c(0, 100, 250, 500, 1000, 2500, 5000, 10000, 30000)
pal <- colorBin(palette = "OrRd", bins = bins, na.color = "#D3D3D3")

# create a map for 1970
leaflet(data = incarceration_1970_map) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>%
  setView(-95.7129, 37.0902, zoom = 3) %>%
  addPolygons(fillColor = ~ pal(total_jail_pop_rate),
              stroke = FALSE,
              smoothFactor = .5,
              opacity = 1,
              fillOpacity = 0.7,
              highlightOptions = highlightOptions(weight = 5,
                                                  fillOpacity = 1,
                                                  color = "black",
                                                  bringToFront = TRUE),
              popup = ~ paste0("County Name: ", county_name %>% str_to_title(), "<br>",
                               "State: ", state %>% str_to_title(), "<br>",
                               "Total Jail Population: ", total_jail_pop, "<br>",
                               "Total Jail-Population rate: ",
                                  total_jail_pop_rate %>% round(2))) %>%
  addLegend("bottomright",
            pal = pal,
            values = ~ total_jail_pop_rate,
            title = "Total Jail Population Rate (per 100,000",
            opacity = 0.7)

# create a map for 2018
leaflet(data = incarceration_2018_map) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>%
  setView(-95.7129, 37.0902, zoom = 3) %>%
  addPolygons(fillColor = ~ pal(total_jail_pop_rate),
              stroke = FALSE,
              smoothFactor = .5,
              opacity = 1,
              fillOpacity = 0.7,
              highlightOptions = highlightOptions(weight = 5,
                                                  fillOpacity = 1,
                                                  color = "black",
                                                  bringToFront = TRUE),
              popup = ~ paste0("County Name: ", county_name %>% str_to_title(), "<br>",
                               "State: ", state %>% str_to_title(), "<br>",
                               "Total Jail Population: ", total_jail_pop, "<br>",
                               "Total Jail-Population rate: ",
                                  total_jail_pop_rate %>% round(2)))

```

# Timelaspe Incarcerated Population
```{r, eval = TRUE}
incarceration_populations_longer <- incarceration_populations %>%
  # select the columns needed for graphing
  select(year, total_supervised, total_incarcerated, local_jail, state_prison, federal_prison) %>%
  # pivot longer the `incarceration_populations` dataset to have all the variables
#under one column named "variables"
  pivot_longer(!year, names_to = "variables", values_to = "counts") %>%
  # convert entries under "variables" into factors
  mutate(variables = as.factor(variables),
         # take out the "_" between words
         variables = str_replace(variables, "_", " "))

# create a time-laspe using gganimate
incarceration_time_animation <- ggplot(data = incarceration_populations_longer, aes(x = year, y = counts)) + 
  geom_line(aes(group = variables, color = variables)) +
  # add title, subtitle, and labels for axis and legend
  labs(title = "Change in Incarceration Population Overtime",
       subtitle = "1980 - 2018",
       x = "Year",
       y = "Number of People",
       color = "Type") +
  # change font sizes for title, subtitle, legend, and x-axis labels
  theme(plot.title = element_text(family = "serif", size = 30),
        plot.subtitle = element_text(family = "serif", size = 24),
        legend.title = element_text(family = "serif", size = 18),
        legend.key.size = unit(1, 'cm'),
        legend.text = element_text(family = "serif", size = 14),
        # change the axis label sizes and adjust the label angle of the x axis
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 30, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12)) +
  # adjust the max, min, and interval for both axes
  scale_y_continuous(breaks = seq(0, 7000000, by = 1000000),
                     labels = comma) +
  scale_x_continuous(breaks = seq(1980, 2018, by = 2)) +
  # set time laspe interval as by each year
  transition_reveal(year)

animate(incarceration_time_animation)

# save the animation as a gif
anim_save("incarceration_time_series.gif", incarceration_time_animation, height = 600, width = 800)
```